name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Build and analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu' # Alternative distribution options are available.
      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SPRING_DATA_MONGODB_URI: ${{ secrets.MONGODB_URI }}
          SPRING_DATA_MONGODB_DATABASE: ${{ secrets.MONGODB_DATABASE }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          AWS_SQS_WEEKLY_SENTIMENT_QUEUE_URL: ${{ secrets.AWS_SQS_WEEKLY_SENTIMENT_QUEUE_URL }}
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          WEATHER_API_KEY: ${{ secrets.WEATHER_API_KEY }}
        run: mvn -B verify -Dsonar.projectKey=Ridhampatel23_journalApp -Dsonar.organization=ridhampatel23  -Daws.sqs.weekly-sentiment-queue-url="${AWS_SQS_WEEKLY_SENTIMENT_QUEUE_URL}"